spring.application.name=project-margit

spring.datasource.url=jdbc:postgresql://localhost:5432/project-margit
spring.datasource.username=postgres
spring.datasource.password=91800610
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate

spring.jackson.deserialization.fail-on-unknown-properties=true
