CREATE TABLE products (
    id UUID PRIMARY KEY NOT NULL DEFAULT GEN_RANDOM_UUID (),
    name VARCHAR(255) NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    product_add_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
)